### ISSUE TITLE
Request On Training Data

### ISSUE THREAD

**Issue by TKTSWalker** [OrigamiDream/gato#3]
Hello, I have been watching the project for some time now and would like to help in any way possible!

My main goals pertain to the game engine NPC capabilities, video understanding, robot control and chatbot!

If I were going to turn these into usable traning data with the current tools I have or can buy, what would you suggest?

Also have there been any tests with any training datasets yet?

**Comment by OrigamiDream** [comment]
Since I am not familiar with reinforcement learning, hence I can't recommend any of tools for RL dataset generation for the NPC tasks.
And also, Gato in this repo haven't yet been tested with any of datasets.
It's just model architecture now.

**Comment by OrigamiDream** [comment]
Issue has been closed due to there are no more conversations.
