### ISSUE TITLE
Do tokens overlap between environments?

### ISSUE THREAD

**Issue by davidADSP** [OrigamiDream/gato#4]
It's not clear from the paper if discrete tokens (for example actions) overlap between environments.

For example presumably if there is an action 13 in two different environments, these aren't embedded to the same vector? Does this mean every environment needs it own embedding table for actions?

**Comment by OrigamiDream** [comment]
In the paper, they have mixed the tasks in a single batch, and there was no sign of use of task-encoding that helps creating embeddings for every single task.
Therefore, it is impossible to use different embeddings for all tasks.

Eventually, as you mentioned, the action token 13 will always be same vector no matter what current environmemt(task) is.

But I still don't know how they had mixed regular supervised task and reinforcement task in a single batch.

**Comment by davidADSP** [comment]
The only sign that I saw that could indicate an environment specific (rather than task specific) embedding was the 'e' subscript on the weights (theta) for the embedding.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/22745344/229354121-2fd64589-7b27-4f9b-812c-ddcbfb950c99.png">

Perhaps this means that it's a different embedding function for every environment?

**Comment by OrigamiDream** [comment]
It just means 'e'mbedding.

Just $\theta$ means all of the weights in the model.
Therefore I guess they had explicitly notated for the embedding-specific parameter: $\theta_e$

**Comment by davidADSP** [comment]
ok - so are we to assume that the action space of say Sokoban and Atari are embedded identically - i.e the embedding for  'Push Down' (2) in sokoban is the same as 'Up' (2) in Atari?

Sokoban
<img width="821" alt="image" src="https://user-images.githubusercontent.com/22745344/229358552-94abb003-df99-44a6-98cf-8843a4aa668f.png">

Atari
<img width="562" alt="image" src="https://user-images.githubusercontent.com/22745344/229358569-3b741b50-c5c3-4e48-85d3-2ec43806f26a.png">

**Comment by davidADSP** [comment]
That seems really strange to me - why not embed them differently? I don't get the benefit of having one embedding function for the discrete aspects (makes sense for continuous, text and image), but it seems to be that way in the paper like you say.

Also, do you know if any of the environments in the Gato paper have discrete elements in their observation spaces? Or are they all continuous, text and image?

**Comment by OrigamiDream** [comment]
Now I understand what you want to say.

They reserved 1024 tokens for just discrete tokens.
It is enough space to reserve tokens for different tasks.

This means:
Action token 13 is always same vector across all environments.
However, "NOOP" (for example) actions are can be different across the environments.
The NOOP can be 246 in Atari, or can be 875 in Sokoban.
But action tokens 246 is always same vector across all environments.
Do you understand what I'm talking about?

Clearly, I couldn't find about how they reserves discrete tokens across tasks.
But what you should know is,
Action token "13" is always come through embedding function E. Not E1 for Atari, E2 for Sokoban, etc.

Therefore, the discrete tokens are embedded in "single embedding function", but they does not seem sharing same index in the table you posted.

**Comment by davidADSP** [comment]
That's completely clear - thank you!

One follow up question in that case - the continuous discretised tokens are shifted so that they don't overlap with the text tokens. Do you know why the discrete tokens are not shifted as well? If they are kept to the range 0-1023 then they would overlap with some of the text tokens it seems?

**Comment by OrigamiDream** [comment]
I guess there would be few options:
1. Discrete tokens and text tokens are overlapped in first 1024 tokens.
→ The model can distinguish the text and discrete tokens because discrete tokens does not have local observation embedding.
2. Discrete tokens are also shifted, but not mentioned in the paper.
→ This is the most clear way.
3. They had made action-exclusive embedding function.
→ The discrete tokens are coming through embedding function $E_{a}$. However, In the case, continuous action tokens also must be came through the exclusive embedding function. This does not make sense because the continuous actions are already shifted into range of [32000, 33024) after discretization.
4. The discrete and continuous tokens share spaces within the range of [32000, 33024].
→ I don't believe in this, but this is also possible.

Well, I believe they had decided not to mention about the discrete token shifting or they just forgot.

**Comment by davidADSP** [comment]
Thanks that matches with my understand as well - thanks for your help, very useful!
